// Generated by gencpp from file swarmRobot/UpdateShape.msg
// DO NOT EDIT!


#ifndef SWARMROBOT_MESSAGE_UPDATESHAPE_H
#define SWARMROBOT_MESSAGE_UPDATESHAPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarmRobot
{
template <class ContainerAllocator>
struct UpdateShape_
{
  typedef UpdateShape_<ContainerAllocator> Type;

  UpdateShape_()
    : pos_x(0.0)
    , pos_y(0.0)
    , mission_index(0)  {
    }
  UpdateShape_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)
    , mission_index(0)  {
  (void)_alloc;
    }



   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef uint32_t _mission_index_type;
  _mission_index_type mission_index;





  typedef boost::shared_ptr< ::swarmRobot::UpdateShape_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarmRobot::UpdateShape_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateShape_

typedef ::swarmRobot::UpdateShape_<std::allocator<void> > UpdateShape;

typedef boost::shared_ptr< ::swarmRobot::UpdateShape > UpdateShapePtr;
typedef boost::shared_ptr< ::swarmRobot::UpdateShape const> UpdateShapeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarmRobot::UpdateShape_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarmRobot::UpdateShape_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swarmRobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'swarmRobot': ['/home/smanier/catkin_ws/src/swarmRobot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swarmRobot::UpdateShape_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmRobot::UpdateShape_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmRobot::UpdateShape_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmRobot::UpdateShape_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmRobot::UpdateShape_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmRobot::UpdateShape_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarmRobot::UpdateShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9408e155321fa630ab5dfc682ac36fd";
  }

  static const char* value(const ::swarmRobot::UpdateShape_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9408e155321fa63ULL;
  static const uint64_t static_value2 = 0x0ab5dfc682ac36fdULL;
};

template<class ContainerAllocator>
struct DataType< ::swarmRobot::UpdateShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmRobot/UpdateShape";
  }

  static const char* value(const ::swarmRobot::UpdateShape_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarmRobot::UpdateShape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_x\n\
float32 pos_y\n\
\n\
uint32 mission_index\n\
";
  }

  static const char* value(const ::swarmRobot::UpdateShape_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarmRobot::UpdateShape_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.mission_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateShape_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarmRobot::UpdateShape_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarmRobot::UpdateShape_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "mission_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mission_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARMROBOT_MESSAGE_UPDATESHAPE_H
